I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/level3.rpy", line 221, in script
    $ renpy.load('checkpoint')
  File "game/level3.rpy", line 221, in <module>
    $ renpy.load('checkpoint')
AttributeError: 'NoneType' object has no attribute 'load'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/level3.rpy", line 221, in script
    $ renpy.load('checkpoint')
  File "C:\Users\uliru\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\uliru\Desktop\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/level3.rpy", line 221, in <module>
    $ renpy.load('checkpoint')
  File "C:\Users\uliru\Desktop\renpy-8.1.3-sdk\renpy\loadsave.py", line 810, in load
    log_data, signature = location.load(filename)
  File "C:\Users\uliru\Desktop\renpy-8.1.3-sdk\renpy\savelocation.py", line 520, in load
    return l.load(slotname) # type: ignore
AttributeError: 'NoneType' object has no attribute 'load'

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
It Gazes Back 1.0
Mon Oct  2 12:41:57 2023
